### ISSUE TITLE
Sample code?

### ISSUE THREAD

**Issue by aaroncalderon** [cansik/smooth-servo#2]
Would it be possible to provide some sample code that explains how to use the following?

- start (with easing)
- motion (linear)
- end (with easing)

**Comment by cansik** [comment]
As already mentioned in the PR answer, there is no code at the moment. The project was intended to be implemented for arduino, but it was decided to use the processing code and send all the servo commands directly to the arduino. So no smooth calculation for arduino. 

But the processing code is in the repo and could be used as starting point to develop an arduino library.
